import {createTypes} from 'reduxsauce'

export default createTypes(`
  GET_SALE_ORDERS
  GET_SALE_ORDERS_SUCCESS
  GET_SALE_ORDERS_FAILURE

  GET_SALE_ORDER
  GET_SALE_ORDER_SUCCESS
  GET_SALE_ORDER_FAILURE

  CREATE_SALE_ORDER
  CREATE_SALE_ORDER_SUCCESS
  CREATE_SALE_ORDER_FAILURE

  RESET_SALE_ORDERS
`)