import {createTypes} from 'reduxsauce'

export default createTypes(`
  GET_PRODUCT_CATEGORIES
  GET_PRODUCT_CATEGORIES_SUCCESS
  GET_PRODUCT_CATEGORIES_FAILURE

  GET_PRODUCT_CATEGORY
  GET_PRODUCT_CATEGORY_SUCCESS
  GET_PRODUCT_CATEGORY_FAILURE

  CREATE_PRODUCT_CATEGORY
  CREATE_PRODUCT_CATEGORY_SUCCESS
  CREATE_PRODUCT_CATEGORY_FAILURE

  UPDATE_PRODUCT_CATEGORY
  UPDATE_PRODUCT_CATEGORY_SUCCESS
  UPDATE_PRODUCT_CATEGORY_FAILURE

  DELETE_PRODUCT_CATEGORY
  DELETE_PRODUCT_CATEGORY_SUCCESS
  DELETE_PRODUCT_CATEGORY_FAILURE

  RESET_PRODUCT_CATEGORY
`)